version: '3.8'

services:
  ssh:
    build: .
    hostname: example
    volumes:
      - ./public:/data/example_www
    ports:
      - "0.0.0.0:2200:22"
    environment:
      - APPLICATION_USER=application
      - APPLICATION_GROUP=application
      - SFTP_ONLY=0
      - PASSWORD=Admin123!
      - SSH_KEYS_ONLY=0
      - SSH_PUBLIC_KEY=ssh-rsa AB...iQ== user@example.org
      - SHELL=zsh
