version: "3.8"

services:
  ssh:
    image: cyb10101/ssh:latest
    restart: always
    hostname: example
    volumes:
      - ./public:/data/example_www
    ports:
      - "0.0.0.0:2200:22"
    environment:
      - TZ=Europe/Berlin
      - LANG=de_DE.UTF-8
      - APPLICATION_USER=application
      - APPLICATION_GROUP=application
      - PASSWORD=Admin123!
      #- SSH_KEYS_ONLY=1
      #- SSH_PUBLIC_KEY=ssh-rsa AB...iQ== user@example.org
      #- ENABLE_SHELL=1
      - SHELL=zsh
    cap_add:
      - NET_ADMIN
      - NET_RAW
